#ifndef error_HEADER
#define error_HEADER

#include <string.h>

// from main.c
#define FUZZER_ERROR_THREAD_MALLOC_FAIL 1

// from fuzzer.h
#define FUZZER_ENGINE_ERROR_MALLOC_FAIL                      10001
#define FUZZER_ENGINE_ERROR_ELEMENT_MISSING_TERMINATOR       10002
#define FUZZER_ENGINE_ERROR_ELEMENT_MISSING_ASSIGNER         10003
#define FUZZER_ENGINE_ERROR_ELEMENT_TOO_LARGE                10004
#define FUZZER_ENGINE_ERROR_ELEMENT_MALLOC_ERROR             10005
#define FUZZER_ENGINE_ERROR_TOKEN_MALLOC_ERROR               10006
#define FUZZER_ENGINE_ERROR_ELEMENT_APPEND                   10007
#define FUZZER_ENGINE_ERROR_TOKEN_MALLOC_FAIL                10008
#define FUZZER_ENGINE_ERROR_TOKEN_TYPE_NOT_FOUND             10009
#define FUZZER_ENGINE_ERROR_TOKEN_ASCII_MALLOC_FAIL          10010
#define FUZZER_ENGINE_ERROR_TOKEN_ASCII_MIN_LENGTH_NOT_FOUND 10011
#define FUZZER_ENGINE_ERROR_TOKEN_ASCII_MAX_LENGTH_NOT_FOUND 10012
#define FUZZER_ENGINE_ERROR_TOKEN_ASCII_MIN_LENGTH_ATOI      10013
#define FUZZER_ENGINE_ERROR_TOKEN_ASCII_MAX_LENGTH_ATOI      10014
#define FUZZER_ENGINE_ERROR_NOT_VALID_ATOI                   10015
#define FUZZER_ENGINE_ERROR_FUZZER_TOKEN_APPEND              10016
#define FUZZER_ENGINE_ERROR_APPEND_REALLOC_FAIL              10017
#define FUZZER_ENGINE_ERROR_TOKEN_ASCII_EXECUTE_MALLOC_FAIL  10018
#define FUZZER_ENGINE_ERROR_TOKEN_BYTE_MALLOC_FAIL           10019
#define FUZZER_ENGINE_ERROR_TOKEN_BYTE_MIN_LENGTH_NOT_FOUND  10020
#define FUZZER_ENGINE_ERROR_TOKEN_BYTE_MAX_LENGTH_NOT_FOUND  10021
#define FUZZER_ENGINE_ERROR_TOKEN_BYTE_MIN_LENGTH_ATOI       10022
#define FUZZER_ENGINE_ERROR_TOKEN_BYTE_MAX_LENGTH_ATOI       10023
#define FUZZER_ENGINE_ERROR_BYTE_EXECUTE_MALLOC_FAIL         10024
#define FUZZER_ENGINE_ERROR_TOKEN_FILE_MALLOC_FAIL           10025
#define FUZZER_ENGINE_ERROR_FILE_FILENAME_NOT_FOUND          10026
#define FUZZER_ENGINE_ERROR_FILE_COULD_NOT_OPEN_FILE         10027
#define FUZZER_ENGINE_ERROR_FILE_READ_ERROR                  10028

// from network.h
#define FUZZER_ERROR_GETADDR_INFO 20000
#define FUZZER_ERROR_INFO_MALLOC_FAIL 20001
#define FUZZER_ERROR_SOCKET_CREATE 20002
#define FUZZER_ERROR_CONNECTION_REFUSED 20003
#define FUZZER_ERROR_ADDRESS_NOT_AVAILABLE 20004
#define FUZZER_ERROR_NETWORK_UNREACHABLE 20005
#define FUZZER_ERROR_INVALID_FAMILY 20006
#define FUZZER_ERROR_CONNECT_UNKNOWN 20007
#define FUZZER_ERROR_SOCKET_CLOSED_ON_SEND 20008
#define FUZZER_ERROR_RECV_UNKNOWN 20009
#define FUZZER_ERROR_HOST_UNREACHABLE 20010


#define FUZZER_ERROR_CUSTOM_MAX_LENGTH 256

extern char FUZZER_ERROR_CUSTOM[256];
extern int fuzzer_errno;


void reset_fuzzer_error_custom ();
char * fuzzer_error_string (int error);


#endif
